<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Aws2Azure.PerfTests</RootNamespace>
    <IsAotCompatible>false</IsAotCompatible>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.3" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.10" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.10" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.4" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Xunit.SkippableFact" Version="1.5.61" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aws2Azure.IntegrationTests\Aws2Azure.IntegrationTests.csproj" />
    <ProjectReference Include="..\Aws2Azure.UnitTests\Aws2Azure.UnitTests.csproj" />
    <ProjectReference Include="..\..\src\Aws2Azure.Amqp\Aws2Azure.Amqp.csproj" />
    <ProjectReference Include="..\..\src\Aws2Azure.Modules.Sqs\Aws2Azure.Modules.Sqs.csproj" />
    <ProjectReference Include="..\..\src\Aws2Azure.Modules.DynamoDb\Aws2Azure.Modules.DynamoDb.csproj" />
  </ItemGroup>
</Project>
