using System.Text;
using System.Text.Json.Nodes;

namespace Aws2Azure.ConfigSchema;

/// <summary>
/// Renders the human field inventory from the canonical JSON Schema. Property
/// paths, types, defaults, discriminator applicability, and scalar constraints
/// therefore cannot drift independently from the authoring profile.
/// </summary>
public static class ConfigurationReferenceGenerator
{
    public const string ArtifactRelativePath = "docs/configuration-reference.md";

    public static string Generate()
    {
        var root = JsonNode.Parse(ConfigSchemaGenerator.Generate())!.AsObject();
        var rows = new List<FieldRow>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        WalkObject(root, root, string.Empty, string.Empty, rows, seen);

        rows.Sort(static (left, right) =>
        {
            var path = StringComparer.Ordinal.Compare(left.Path, right.Path);
            return path != 0
                ? path
                : StringComparer.Ordinal.Compare(left.Applicability, right.Applicability);
        });

        var output = new StringBuilder();
        output.AppendLine("# Complete configuration field reference");
        output.AppendLine();
        output.AppendLine(
            "This page is generated by `tools/Aws2Azure.ConfigSchema` from the canonical");
        output.AppendLine(
            "[`config.schema.json`](../config.schema.json) authoring profile and its");
        output.AppendLine(
            "source-generated `ConfigDocument` contract. Do not hand-edit the field table.");
        output.AppendLine();
        output.AppendLine(
            "A path ending in `[]` is an array item. `<name>` is an operator-selected map key.");
        output.AppendLine(
            "Rows repeat where a discriminator changes a property's requirements. `None` means");
        output.AppendLine(
            "the property has no schema default; omission is distinct from an empty value.");
        output.AppendLine();
        output.AppendLine("| JSON path | Type | Default | Applicability | Validation |");
        output.AppendLine("|---|---|---|---|---|");
        foreach (var row in rows)
        {
            output
                .Append("| `").Append(Escape(row.Path)).Append("` | ")
                .Append(Escape(row.Type)).Append(" | ")
                .Append(Escape(row.Default)).Append(" | ")
                .Append(Escape(row.Applicability)).Append(" | ")
                .Append(Escape(row.Validation)).AppendLine(" |");
        }

        var constraints = new HashSet<string>(StringComparer.Ordinal);
        CollectConstraintDescriptions(root, constraints);
        if (constraints.Count > 0)
        {
            output.AppendLine();
            output.AppendLine("## Cross-field requirements");
            output.AppendLine();
            output.AppendLine(
                "The schema also enforces these conditions across otherwise optional fields:");
            output.AppendLine();
            foreach (var constraint in constraints.Order(StringComparer.Ordinal))
            {
                output.Append("- ").AppendLine(constraint);
            }
        }

        output.AppendLine();
        output.AppendLine("## Authoring profile versus v1 runtime reads");
        output.AppendLine();
        output.AppendLine(
            "The table describes canonical authoring. New and edited files should use the exact");
        output.AppendLine(
            "property names and string values shown here and pass schema validation. Runtime");
        output.AppendLine(
            "reads remain a v1-compatible superset: property names are case-insensitive, unknown");
        output.AppendLine(
            "extension members are ignored, defined numeric enum tokens and whitespace-padded");
        output.AppendLine(
            "enum/backend values are accepted, and known fields outside the selected");
        output.AppendLine(
            "backend/auth shape are ignored. Serialization always emits canonical names.");
        output.AppendLine();
        output.AppendLine(
            "The legacy standalone SNS `kind: eventGrid` runtime shape is also outside the");
        output.AppendLine(
            "authoring profile. Migrate it to `kind: serviceBusTopics` plus");
        output.AppendLine(
            "`eventGridFallback`; see [Operator configuration schema](configuration-schema.md).");
        output.AppendLine();
        output.AppendLine("## Related operator references");
        output.AppendLine();
        output.AppendLine(
            "- [Process environment variables and JSON overrides](configuration-environment.md)");
        output.AppendLine("- [Production configuration examples](configuration-examples.md)");
        output.AppendLine("- [Configuration and adoption troubleshooting](troubleshooting.md)");
        output.AppendLine("- [Shortest-path adoption checklist](adoption.md)");

        return output.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static void WalkObject(
        JsonObject root,
        JsonObject schema,
        string path,
        string discriminator,
        List<FieldRow> rows,
        HashSet<string> seen)
    {
        schema = Resolve(root, schema);
        if (schema["properties"] is not JsonObject properties)
        {
            if (schema["additionalProperties"] is JsonObject mapValue)
            {
                WalkSchema(root, mapValue, Append(path, "<name>"), discriminator, false, rows, seen);
            }
            return;
        }

        var required = schema["required"] is JsonArray requiredArray
            ? requiredArray
                .Select(static item => item?.GetValue<string>())
                .Where(static item => item is not null)
                .ToHashSet(StringComparer.Ordinal)
            : [];

        foreach (var (name, propertyNode) in properties)
        {
            if (propertyNode is not JsonObject property)
            {
                continue;
            }

            var resolved = Resolve(root, property);
            if (IsNullOnly(resolved))
            {
                continue;
            }

            WalkSchema(
                root,
                property,
                Append(path, name),
                discriminator,
                required.Contains(name),
                rows,
                seen);
        }
    }

    private static void WalkSchema(
        JsonObject root,
        JsonObject schema,
        string path,
        string discriminator,
        bool required,
        List<FieldRow> rows,
        HashSet<string> seen)
    {
        var rowSchema = Resolve(root, schema);
        var structuralSchema = rowSchema;
        var variants = NonNullVariants(rowSchema);
        var objectVariants = variants
            .Select(variant => Resolve(root, variant))
            .Where(variant => GetPrimaryType(root, variant) == "object")
            .ToArray();
        if (variants.Count > 1
            && objectVariants.Length == variants.Count
            && objectVariants.All(variant => FindDiscriminator(root, variant).Length > 0))
        {
            foreach (var variantObject in objectVariants)
            {
                var variantDiscriminator = FindDiscriminator(root, variantObject);
                WalkSchema(
                    root,
                    variantObject,
                    path,
                    JoinDiscriminator(discriminator, variantDiscriminator),
                    required,
                    rows,
                    seen);
            }
            return;
        }

        if (variants.Count == 1)
        {
            var candidate = Resolve(root, variants[0]);
            var candidateType = GetPrimaryType(root, candidate);
            if (candidateType is "object" or "array")
            {
                structuralSchema = candidate;
            }
        }

        AddRow(root, rowSchema, path, discriminator, required, rows, seen);

        var type = GetPrimaryType(root, structuralSchema);
        if (type == "object")
        {
            WalkObject(root, structuralSchema, path, discriminator, rows, seen);
        }
        else if (type == "array" && structuralSchema["items"] is JsonObject items)
        {
            WalkSchema(root, items, path + "[]", discriminator, true, rows, seen);
        }
    }

    private static void AddRow(
        JsonObject root,
        JsonObject schema,
        string path,
        string discriminator,
        bool required,
        List<FieldRow> rows,
        HashSet<string> seen)
    {
        var applicability = InferApplicability(path, discriminator);
        var key = path + "\n" + applicability + "\n" + required;
        if (!seen.Add(key))
        {
            return;
        }

        rows.Add(new FieldRow(
            path,
            DescribeType(root, schema),
            DescribeDefault(root, schema),
            applicability,
            DescribeValidation(root, schema, required)));
    }

    private static string DescribeType(JsonObject root, JsonObject schema)
    {
        schema = Resolve(root, schema);
        var nullable = AllowsNull(root, schema);
        var variants = schema["type"] is JsonValue
            ? []
            : NonNullVariants(schema, includeAnyOf: true);
        var types = variants.Count > 0
            ? variants.Select(variant => GetPrimaryType(root, variant)).Distinct(StringComparer.Ordinal).ToArray()
            : [GetPrimaryType(root, schema)];
        var type = string.Join(" or ", types.Select(static value => value switch
        {
            "array" => "array",
            "object" => "object",
            "integer" => "integer",
            "boolean" => "boolean",
            "string" => "string",
            _ => value,
        }));

        if (types.Length == 1 && types[0] == "object")
        {
            var resolved = variants.Count == 1 ? Resolve(root, variants[0]) : schema;
            if (resolved["additionalProperties"] is JsonObject)
            {
                type = "map";
            }
        }
        else if (types.Length == 1 && types[0] == "array")
        {
            var resolved = variants.Count == 1 ? Resolve(root, variants[0]) : schema;
            if (resolved["items"] is JsonObject items)
            {
                type = $"array<{GetPrimaryType(root, items)}>";
            }
        }

        return nullable ? type + " or null" : type;
    }

    private static string DescribeDefault(JsonObject root, JsonObject schema)
    {
        schema = Resolve(root, schema);
        if (schema["default"] is JsonValue direct)
        {
            return FormatValue(direct);
        }

        foreach (var variant in NonNullVariants(schema, includeAnyOf: true))
        {
            var resolved = Resolve(root, variant);
            if (resolved["default"] is JsonValue value)
            {
                return FormatValue(value);
            }
        }

        return "None";
    }

    private static string DescribeValidation(
        JsonObject root,
        JsonObject schema,
        bool required)
    {
        schema = Resolve(root, schema);
        var parts = new List<string> { required ? "Required." : "Optional." };
        var variants = NonNullVariants(schema, includeAnyOf: true);
        var effective = variants.Count == 1 ? Resolve(root, variants[0]) : schema;

        if (effective["description"] is JsonValue description)
        {
            parts.Add(description.GetValue<string>());
        }

        var literals = FindLiterals(root, schema);
        if (literals.Count > 0)
        {
            parts.Add("Values: " + string.Join(", ", literals.Select(static value => $"`{value}`")) + ".");
        }

        var patterns = new List<string>();
        CollectPatterns(root, schema, patterns);
        var schemes = FindUriSchemes(root, schema);
        if (schemes.Count > 0)
        {
            parts.Add("Absolute URI; schemes: " + string.Join(", ", schemes.Select(static value => $"`{value}`")) + ".");
        }
        foreach (var pattern in patterns.Distinct(StringComparer.Ordinal))
        {
            if (pattern == "\\S")
            {
                parts.Add("Must contain a non-whitespace character.");
            }
        }
        if (ContainsEmptyStringVariant(root, schema))
        {
            parts.Add(
                "Empty string is treated as omitted; the backend uses its configured or derived endpoint.");
        }

        if (effective["minLength"] is JsonValue minLength)
        {
            parts.Add($"Minimum length {minLength.GetValue<int>()}.");
        }
        if (effective["minItems"] is JsonValue minItems)
        {
            parts.Add($"At least {minItems.GetValue<int>()} item(s).");
        }
        if (effective["uniqueItems"] is JsonValue uniqueItems
            && uniqueItems.TryGetValue<bool>(out var itemsAreUnique)
            && itemsAreUnique)
        {
            parts.Add("Items must be unique.");
        }
        if (effective["minimum"] is JsonValue minimum)
        {
            parts.Add($"Minimum {minimum.GetValue<int>()}.");
        }
        if (effective["contentEncoding"] is JsonValue encoding)
        {
            parts.Add($"Encoding: {encoding.GetValue<string>()}.");
        }
        if (effective["additionalProperties"] is JsonValue additionalProperties
            && additionalProperties.TryGetValue<bool>(out var acceptsAdditionalProperties)
            && !acceptsAdditionalProperties)
        {
            parts.Add("Unknown properties rejected by the authoring schema.");
        }
        if (effective["anyOf"] is JsonArray alternatives)
        {
            var requiredAlternatives = alternatives
                .OfType<JsonObject>()
                .Select(variant => variant["required"] as JsonArray)
                .Where(static requiredNames => requiredNames is not null)
                .Select(requiredNames => string.Join(
                    " + ",
                    requiredNames!.Select(static item => $"`{item!.GetValue<string>()}`")))
                .Where(static names => names.Length > 0)
                .ToArray();
            if (requiredAlternatives.Length > 0)
            {
                parts.Add("Requires one of: " + string.Join("; ", requiredAlternatives) + ".");
            }
        }

        return string.Join(" ", parts.Distinct(StringComparer.Ordinal));
    }

    private static string GetPrimaryType(JsonObject root, JsonObject schema)
    {
        schema = Resolve(root, schema);
        if (schema["type"] is JsonValue type)
        {
            return type.GetValue<string>();
        }

        var variants = NonNullVariants(schema, includeAnyOf: true);
        return variants.Count > 0
            ? GetPrimaryType(root, variants[0])
            : "conditional";
    }

    private static List<JsonObject> NonNullVariants(
        JsonObject schema,
        bool includeAnyOf = false)
    {
        var result = new List<JsonObject>();
        var alternatives = schema["oneOf"] as JsonArray;
        if (alternatives is null && includeAnyOf)
        {
            alternatives = schema["anyOf"] as JsonArray;
        }
        if (alternatives is null)
        {
            return result;
        }

        foreach (var item in alternatives)
        {
            if (item is JsonObject variant && !IsNullOnly(variant))
            {
                result.Add(variant);
            }
        }
        return result;
    }

    private static bool AllowsNull(JsonObject root, JsonObject schema)
    {
        schema = Resolve(root, schema);
        if (IsNullOnly(schema))
        {
            return true;
        }

        var alternatives = schema["oneOf"] as JsonArray ?? schema["anyOf"] as JsonArray;
        return alternatives is not null
            && alternatives.Any(item => item is JsonObject variant && IsNullOnly(Resolve(root, variant)));
    }

    private static bool ContainsEmptyStringVariant(JsonObject root, JsonObject schema)
        => FindLiterals(root, schema, includeEmpty: true)
            .Contains(string.Empty, StringComparer.Ordinal);

    private static bool IsNullOnly(JsonObject schema)
        => schema["type"] is JsonValue value
            && value.TryGetValue<string>(out var type)
            && type == "null";

    private static JsonObject Resolve(JsonObject root, JsonObject schema)
    {
        var current = schema;
        var visited = new HashSet<string>(StringComparer.Ordinal);
        while (current["$ref"] is JsonValue referenceValue)
        {
            var reference = referenceValue.GetValue<string>();
            const string prefix = "#/$defs/";
            if (!reference.StartsWith(prefix, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Unsupported configuration schema reference '{reference}'.");
            }
            if (!visited.Add(reference))
            {
                throw new InvalidOperationException(
                    $"Cyclic configuration schema reference '{reference}'.");
            }
            current = root["$defs"]![reference[prefix.Length..]]!.AsObject();
        }

        return current;
    }

    private static string FindDiscriminator(JsonObject root, JsonObject schema)
    {
        schema = Resolve(root, schema);
        if (schema["properties"] is not JsonObject properties)
        {
            return string.Empty;
        }

        foreach (var name in new[] { "kind", "mode", "authMode", "backend" })
        {
            if (properties[name] is not JsonObject property)
            {
                continue;
            }

            var literals = FindLiterals(root, property);
            if (literals.Count == 1)
            {
                return $"{name}={literals[0]}";
            }
        }

        return string.Empty;
    }

    private static List<string> FindLiterals(
        JsonObject root,
        JsonObject schema,
        bool includeEmpty = false)
    {
        var values = new List<string>();
        CollectStringAnnotations(
            root,
            schema,
            "x-canonical-value",
            "x-canonical-values",
            values);
        return values
            .Where(value => includeEmpty || value.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }

    private static void CollectPatterns(JsonObject root, JsonObject schema, List<string> patterns)
    {
        schema = Resolve(root, schema);
        if (schema["pattern"] is JsonValue pattern)
        {
            patterns.Add(pattern.GetValue<string>());
        }

        var alternatives = schema["oneOf"] as JsonArray ?? schema["anyOf"] as JsonArray;
        if (alternatives is not null)
        {
            foreach (var item in alternatives)
            {
                if (item is JsonObject variant)
                {
                    CollectPatterns(root, variant, patterns);
                }
            }
        }
    }

    private static List<string> FindUriSchemes(JsonObject root, JsonObject schema)
    {
        var values = new List<string>();
        CollectStringAnnotations(root, schema, string.Empty, "x-uri-schemes", values);
        return values.Distinct(StringComparer.Ordinal).ToList();
    }

    private static void CollectStringAnnotations(
        JsonObject root,
        JsonObject schema,
        string scalarName,
        string arrayName,
        List<string> values)
    {
        schema = Resolve(root, schema);
        if (scalarName.Length > 0
            && schema[scalarName] is JsonValue scalar
            && scalar.TryGetValue<string>(out var text))
        {
            values.Add(text);
        }
        if (schema[arrayName] is JsonArray array)
        {
            foreach (var item in array)
            {
                if (item is JsonValue value && value.TryGetValue<string>(out var itemText))
                {
                    values.Add(itemText);
                }
            }
        }

        var alternatives = schema["oneOf"] as JsonArray ?? schema["anyOf"] as JsonArray;
        if (alternatives is null)
        {
            return;
        }
        foreach (var item in alternatives)
        {
            if (item is JsonObject variant)
            {
                CollectStringAnnotations(root, variant, scalarName, arrayName, values);
            }
        }
    }

    private static void CollectConstraintDescriptions(
        JsonNode node,
        HashSet<string> descriptions)
    {
        if (node is JsonObject obj)
        {
            if (obj["x-constraint-description"] is JsonValue description
                && description.TryGetValue<string>(out var text))
            {
                descriptions.Add(text);
            }
            foreach (var (_, child) in obj)
            {
                if (child is not null)
                {
                    CollectConstraintDescriptions(child, descriptions);
                }
            }
        }
        else if (node is JsonArray array)
        {
            foreach (var child in array)
            {
                if (child is not null)
                {
                    CollectConstraintDescriptions(child, descriptions);
                }
            }
        }
    }

    private static string InferApplicability(string path, string discriminator)
    {
        var scope = path switch
        {
            var value when value.StartsWith("services.s3", StringComparison.Ordinal) => "S3 module",
            var value when value.StartsWith("services.sqs", StringComparison.Ordinal) => "SQS module",
            var value when value.StartsWith("services.dynamodb", StringComparison.Ordinal) => "DynamoDB module",
            var value when value.StartsWith("services.sns", StringComparison.Ordinal) => "SNS module",
            var value when value.StartsWith("services.kinesis", StringComparison.Ordinal) => "Kinesis module",
            var value when value.StartsWith("services.secretsmanager", StringComparison.Ordinal) => "Secrets Manager module",
            var value when value.Contains(".azure.s3", StringComparison.Ordinal) => "S3 / Blob backend",
            var value when value.Contains(".azure.sqs", StringComparison.Ordinal) => "SQS / Service Bus backend",
            var value when value.Contains(".azure.dynamodb", StringComparison.Ordinal) => "DynamoDB / Cosmos backend",
            var value when value.Contains(".azure.sns.eventGridFallback", StringComparison.Ordinal) => "SNS Event Grid fallback",
            var value when value.Contains(".azure.sns", StringComparison.Ordinal) => "SNS / Service Bus Topics backend",
            var value when value.Contains(".azure.kinesis", StringComparison.Ordinal) => "Kinesis / Event Hubs backend",
            var value when value.Contains(".azure.secretsmanager", StringComparison.Ordinal) => "Secrets Manager / Key Vault backend",
            var value when value.StartsWith("azureIdentities", StringComparison.Ordinal) => "Named Entra identity",
            var value when value.StartsWith("bindings", StringComparison.Ordinal) => "Each AWS identity binding",
            _ => "Configuration document",
        };

        return string.IsNullOrEmpty(discriminator) ? scope : $"{scope}; `{discriminator}`";
    }

    private static string JoinDiscriminator(string current, string next)
        => string.IsNullOrEmpty(next)
            ? current
            : string.IsNullOrEmpty(current) ? next : current + ", " + next;

    private static string Append(string path, string name)
        => string.IsNullOrEmpty(path) ? name : path + "." + name;

    private static string FormatValue(JsonValue value)
    {
        if (value.TryGetValue<string>(out var text))
        {
            return $"`{text}`";
        }
        if (value.TryGetValue<bool>(out var boolean))
        {
            return boolean ? "`true`" : "`false`";
        }
        return $"`{value.ToJsonString()}`";
    }

    private static string Escape(string value)
        => value.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal);

    private sealed record FieldRow(
        string Path,
        string Type,
        string Default,
        string Applicability,
        string Validation);
}
