using System.Text.Json;
using System.Text.Json.Nodes;
using Json.Schema;

namespace Aws2Azure.DocsQuality;

/// <summary>
/// Validates every committed configuration example and every fenced
/// JSON/JSONC configuration snippet in hand-authored documentation against
/// the canonical <c>config.schema.json</c> (generated by
/// <c>tools/Aws2Azure.ConfigSchema</c>, never hand-edited here). This is the
/// "validate examples against the normative configuration schema" gate from
/// issue #770.
/// </summary>
internal static class ConfigExampleValidator
{
    private static readonly JsonDocumentOptions TolerantJsonOptions = new()
    {
        CommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    private static readonly EvaluationOptions EvaluationOptions = new()
    {
        RequireFormatValidation = true,
        OutputFormat = OutputFormat.List,
    };

    public static IReadOnlyList<string> Validate(string repoRoot)
    {
        var violations = new List<string>();
        var schema = LoadSchema(repoRoot);

        violations.AddRange(ValidateCommittedExamples(repoRoot, schema));
        violations.AddRange(ValidateDocumentedSnippets(repoRoot, schema));
        return violations;
    }

    private static JsonSchema LoadSchema(string repoRoot) =>
        JsonSchema.FromText(File.ReadAllText(Path.Combine(repoRoot, "config.schema.json")));

    private static IEnumerable<string> ValidateCommittedExamples(string repoRoot, JsonSchema schema)
    {
        var examplesDir = Path.Combine(repoRoot, "docs", "configuration", "examples");
        if (!Directory.Exists(examplesDir))
        {
            yield break;
        }

        foreach (var file in Directory.EnumerateFiles(examplesDir, "*.json", SearchOption.TopDirectoryOnly)
                     .OrderBy(path => path, StringComparer.Ordinal))
        {
            var relative = Path.GetRelativePath(repoRoot, file).Replace('\\', '/');
            JsonNode? document = null;
            string? parseError = null;
            try
            {
                document = JsonNode.Parse(File.ReadAllText(file), documentOptions: TolerantJsonOptions);
            }
            catch (JsonException exception)
            {
                parseError = exception.Message;
            }

            if (parseError is not null)
            {
                yield return $"{relative}: is not valid JSON ({parseError}).";
                continue;
            }

            foreach (var error in DescribeErrors(schema, document))
            {
                yield return $"{relative}: {error}";
            }
        }
    }

    private static IEnumerable<string> ValidateDocumentedSnippets(string repoRoot, JsonSchema schema)
    {
        foreach (var file in DocTree.MarkdownFiles(repoRoot))
        {
            var relative = DocTree.ToRepoRelative(repoRoot, file);
            var text = File.ReadAllText(file);
            foreach (var block in FencedCodeBlockExtractor.Extract(text))
            {
                if (block.Language is not ("json" or "jsonc"))
                {
                    continue;
                }

                JsonNode? document;
                try
                {
                    document = JsonNode.Parse(block.Content, documentOptions: TolerantJsonOptions);
                }
                catch (JsonException)
                {
                    // Not every fenced json/jsonc block is a full config document
                    // (e.g. a single value or a deliberately partial fragment).
                    // Only blocks that parse cleanly are considered candidates.
                    continue;
                }

                if (document is not JsonObject obj || !LooksLikeConfigDocument(obj))
                {
                    continue;
                }

                foreach (var error in DescribeErrors(schema, document))
                {
                    yield return $"{relative}:{block.StartLine}: {error}";
                }
            }
        }
    }

    // A fenced snippet is treated as a full operator config document only when
    // it plausibly is one (top-level "services" or "bindings"), so unrelated
    // JSON/JSONC examples (partial fragments, unrelated payloads) are ignored.
    private static bool LooksLikeConfigDocument(JsonObject obj) =>
        obj.ContainsKey("services") || obj.ContainsKey("bindings");

    private static IEnumerable<string> DescribeErrors(JsonSchema schema, JsonNode? document)
    {
        var result = schema.Evaluate(document, EvaluationOptions);
        if (result.IsValid)
        {
            yield break;
        }

        foreach (var detail in Flatten(result))
        {
            if (detail.Errors is null)
            {
                continue;
            }
            foreach (var (keyword, message) in detail.Errors)
            {
                var pointer = detail.InstanceLocation.ToString();
                yield return string.IsNullOrEmpty(pointer)
                    ? $"[{keyword}] {message}"
                    : $"at '{pointer}': [{keyword}] {message}";
            }
        }
    }

    private static IEnumerable<EvaluationResults> Flatten(EvaluationResults result)
    {
        yield return result;
        foreach (var detail in result.Details)
        {
            foreach (var nested in Flatten(detail))
            {
                yield return nested;
            }
        }
    }
}
