using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Aws2Azure.GapDocs;

/// <summary>
/// Emits the <c>CapabilityRegistry.g.cs</c> file consumed by Aws2Azure.Core.
/// The registry is the single source of truth at runtime for which operations
/// each module advertises; YAML files are the single source of truth at design
/// time. Keeping them in sync is the whole point of the gap-docs pipeline.
/// </summary>
public static class CodeRenderer
{
    public static void Render(IReadOnlyList<OperationDoc> docs, string outputPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This file is generated by tools/Aws2Azure.GapDocs from docs/gaps/**/*.yaml.");
        sb.AppendLine("//     Do not edit by hand. Run `dotnet run --project tools/Aws2Azure.GapDocs` to regenerate.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Aws2Azure.Core.Modules;");
        sb.AppendLine();
        sb.AppendLine("public static class CapabilityRegistry");
        sb.AppendLine("{");

        var grouped = docs
            .GroupBy(d => d.Service.ToLowerInvariant())
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        foreach (var group in grouped)
        {
            var ops = group.OrderBy(o => o.Operation, StringComparer.Ordinal).ToList();
            var fieldName = ToPascal(group.Key);
            sb.AppendLine($"    public static readonly CapabilityMatrix {fieldName} = new(");
            sb.AppendLine($"        ServiceName: \"{group.Key}\",");
            sb.AppendLine("        Operations: new OperationCapability[]");
            sb.AppendLine("        {");
            foreach (var op in ops)
            {
                var status = MapStatus(op);
                var notes = BuildNotes(op);
                sb.AppendLine($"            new(\"{Escape(op.Operation)}\", OperationStatus.{status}{notes}),");
            }
            sb.AppendLine("        });");
            sb.AppendLine();
        }

        sb.AppendLine("    public static IReadOnlyList<CapabilityMatrix> All { get; } = new[]");
        sb.AppendLine("    {");
        foreach (var group in grouped)
        {
            sb.AppendLine($"        {ToPascal(group.Key)},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        File.WriteAllText(outputPath, sb.ToString());
    }

    private static string MapStatus(OperationDoc op) => op.Status.ToLowerInvariant() switch
    {
        "implemented" => "Implemented",
        "partial" => "Partial",
        "stub" => "Stub",
        "unsupported" => "Unsupported",
        _ => throw new InvalidOperationException(
            $"{op.SourceFile}: unknown operation status '{op.Status}' for {op.Service}/{op.Operation}.")
    };

    private static string BuildNotes(OperationDoc op)
    {
        var lines = new List<string>();
        if (!string.IsNullOrWhiteSpace(op.AzureEquivalent))
        {
            lines.Add("Azure: " + op.AzureEquivalent);
        }
        foreach (var bd in op.BehaviorDifferences)
        {
            lines.Add("Diff: " + bd);
        }
        if (lines.Count == 0) return string.Empty;
        var arr = string.Join(", ", lines.Select(l => "\"" + Escape(l) + "\""));
        return ", new[] { " + arr + " }";
    }

    private static string ToPascal(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;

        if (KnownServiceNames.TryGetValue(s, out var knownName))
        {
            return knownName;
        }

        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    private static readonly IReadOnlyDictionary<string, string> KnownServiceNames =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["dynamodb"] = "DynamoDb",
            ["eventbridge"] = "EventBridge",
            ["secretsmanager"] = "SecretsManager",
            ["stepfunctions"] = "StepFunctions"
        };

    private static string Escape(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
}
